service: fastapi-sls-app-2

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  memorySize: 256
  timeout: 10

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary

custom:
  pythonRequirements:
    dockerizePip: true
    layer: false
    slim: true
    strip: false
  apigwBinary:
    types:
      - 'application/json'
      - 'application/octet-stream'
      - 'application/x-amz-json-1.0'
      - 'application/x-amz-json-1.1'
      - 'image/*'
      - 'text/html'
      - 'text/css'
      - 'text/javascript'
      - 'application/javascript'

